# Default parameters to test wordcount.py script.:
# Script runs in "wordcount" directory.

# Generate automatic checks
auto_check = true

[solution.mimic]

[[solution.mimic.checks]]
command = ["{sys_exe}", "{in_path}", 'small.txt']

[solution.wordcount]

[[solution.wordcount.checks]]
command = ["{sys_exe}", "{in_path}", '--count', 'small.txt']

[[solution.wordcount.checks]]
command = ["{sys_exe}", "{in_path}", '--topcount', 'alice.txt']
