# Default parameters to test copyspecial.py script.
# Script runs in "copyspecial" directory.

# Generate automatic checks
auto_check = true

[solution.copyspecial]

[[solution.copyspecial.checks]]
command = ["{sys_exe}", "{in_path}", "solution"]
