# Default parameters to test logpuzzle.py script.
# Script runs in "logpuzzle" directory.

# Generate automatic checks
auto_check = true

[solution.logpuzzle]

[[solution.logpuzzle.checks]]
command = ["{sys_exe}", "{in_path}", 'animal_code.google.com']
