# Default parameters to test babynames.py script.:
# Script runs in "babynames" directory.

# Generate automatic checks
auto_check = true

[solution.babynames]

[[solution.babynames.checks]]
command = ["{sys_exe}", "{in_path}", "baby1990.html", "baby1992.html", "baby1994.html"]
